version: "3"

services: 
  app:
    build:
      context: .
    container_name: flask_a_z
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
    command: >
       sh -c "python run.py"

      
  # db:
  #   image: postgres:10
  #   environment:
  #     - POSTGRES_DB=app
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=supersecretpassword

